In [ ]:
import numpy as np

In [ ]:
# 1D array

a = np.array([2, 4, 6, 8, 10])
print(a)

[ 2  4  6  8 10]


In [ ]:
# 2D array

b = np.array([[2, 4, 6], [6, 8, 10]])
print(b)

[[ 2  4  6]
 [ 6  8 10]]


In [ ]:
# 3D array

c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(b)
type(a)

numpy.ndarray

In [ ]:
np.array([0, 1, 2, 3, 0], dtype = bool)

array([False,  True,  True,  True, False])

In [ ]:
np.array([1, 2, 3, 4], dtype = float)

array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3, 4], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(5,2)
print(d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
e = np.arange(2, 15, 2)
print(e)

[ 2  4  6  8 10 12 14]


In [ ]:
f = np.arange(1, 13).reshape(2, 6)
print(f)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((4, 5))

array([[0.07169298, 0.63642855, 0.91096271, 0.66839407, 0.8054229 ],
       [0.18316873, 0.30700904, 0.10472507, 0.75930583, 0.60621533],
       [0.44467952, 0.62751945, 0.52408645, 0.91579151, 0.13366339],
       [0.52293372, 0.35319239, 0.1748635 , 0.54290016, 0.95262843]])

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a1 = np.arange(10)   # 1D
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(12, dtype = float).reshape(4, 3)   # 2D (Matrix)
print(x)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
a2 = np.arange(8).reshape(2, 2, 2)   # 3D (Tensor)
print(a2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
