## **Array**

In [1]:
# Array Creation

In [2]:
import numpy as np

**1. Create a 1D NumPy array with values [10, 20, 30, 40, 50].**

In [3]:
a1 = np.array([10, 20, 30, 40, 50])
a1

array([10, 20, 30, 40, 50])

**2. Create a 3×3 matrix filled with zeros using NumPy.**

In [6]:
a2 = np.zeros((3, 3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**3. Create a 1D array of 10 evenly spaced values between 0 and 1.**

In [10]:
a3 = np.linspace(0, 1, 10)
a3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**4. Create an identity matrix of size 4×4.**

In [14]:
a4 = np.identity(4)
a4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**5. Generate an array of integers from 1 to 20 with step 2.**

In [79]:
a5 = np.arange(1, 20, 2)
a5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## **Array Info**

**6. How do you find the shape, size, and data type of a NumPy array?**

In [18]:
# Shape
a4.shape

(4, 4)

In [19]:
# Size
a5.size

10

In [20]:
# Data Type
a3.dtype

dtype('float64')

## **Indexing**

**7. Given arr = [5, 15, 25, 35, 45], access the 3rd element.**

In [21]:
arr = [5, 15, 25, 35, 45]
arr[2]

25

**8. From a 2D array of shape (4,4), extract the element at row 2, column 3.**

In [24]:
b1 = np.array([[2, 4, 6, 8, 10, 12, 14, 16], [1, 3, 5, 7, 9, 11, 13, 15]]).reshape(4, 4)
b1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [25]:
b1[1, 2]

np.int64(14)

## **Slicing**

**9. Slice the last 3 elements from arr = [10, 20, 30, 40, 50].**

In [26]:
arr = [10, 20, 30, 40, 50]
arr[-3:]

[30, 40, 50]

**10. From a 2D array, extract the entire second row.**

In [27]:
b1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [31]:
b1[1:2]

array([[10, 12, 14, 16]])

## **Math Operations**

**11. Add 5 to every element of an array without using a loop.**

In [32]:
b1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [33]:
b1 + 5

array([[ 7,  9, 11, 13],
       [15, 17, 19, 21],
       [ 6,  8, 10, 12],
       [14, 16, 18, 20]])

**12. Find the sum, min, max, and mean of a NumPy array.**

In [35]:
b1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [37]:
# Sum

np.sum(b1)

np.int64(136)

In [38]:
# Min

np.min(b1)

np.int64(1)

In [39]:
# Max

np.max(b1)

np.int64(16)

In [40]:
# Mean

np.mean(b1)

np.float64(8.5)

**13. Multiply two arrays element-wise.**

In [49]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(2, 14).reshape(3, 4)

In [46]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [51]:
arr1 * arr2

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

## **Reshape**

**14. Reshape a 1D array of 12 elements into a 3×4 matrix.**

In [53]:
r = np.arange(1, 13).reshape(3, 4)
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**15. Flatten a 2D array into a 1D array.**

In [54]:
np.ravel(r)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**16. Access the element at 2nd row, 3rd column in a 2D array**

In [55]:
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
r[1: 2, 2]

array([7])

**17. Slice the first 3 elements from an array.**

In [62]:
a1

array([10, 20, 30, 40, 50])

In [64]:
a1[0:3]

array([10, 20, 30])

**18. Extract the last 2 rows from a 2D array.**

In [65]:
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
r[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**19. Add two arrays element-wise.**

In [67]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
arr2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [69]:
arr1 + arr2

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

**20. Multiply all elements of an array by 5.**

In [70]:
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
s = r * 5
s

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

**21. Find the maximum and minimum values in an array.**

In [76]:
# maximum element

np.max(s)

np.int64(60)

In [77]:
# minimum element

np.min(s)

np.int64(5)

**22. Compute the mean of an array.**

In [78]:
np.mean(s)

np.float64(32.5)